#start vision node request
bool start_request
controller start_ctrl

#abort vision node request
bool abort_request

# For lane marker control
int8 numLanes
int8 chosenLane # 0 is left, 1 is right
---
#start vision node response
bool start_response
# abort vision node response
bool abort_response
controller data
